apiVersion: v1
kind: Namespace
metadata:
  name: chat-api-server

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-api-server-deployment
  namespace: chat-api-server
spec:
  selector:
    matchLabels:
      component: api-server
  template:
    metadata:
      labels:
        component: api-server
    spec:
      serviceAccount: chat-api-server
      containers:
      - image: quay.io/hown3d/chat-api-server:0.0.2
        imagePullPolicy: Always
        name: chat-api-server
        # args: 
        #   - "-devel"
        securityContext:
          runAsUser: 999
          runAsGroup: 999 
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:10000"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:10000"]
          initialDelaySeconds: 10
        ports:
        - containerPort:  10000
          name:  grpc

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: chat-api-server
  namespace: chat-api-server

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chat-api-server
rules:
- apiGroups: ["chat.accso.de"]
  resources: ["rockets"]
  verbs: ["create","delete", "update", "patch", "get", "watch", "list"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "pods/log"]
  verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: ClusterRoleBinding
metadata:
  name: chat-api-server
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: chat-api-server
  namespace: chat-api-server
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: chat-api-server # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io